#ifndef PKI_OSSL_OCSPROV_ASN1_H
#define PKI_OSSL_OCSPROV_ASN1_H
# pragma once

// Local Includes
#include "ocsprov_types.h"

BEGIN_C_DECLS

DECLARE_ASN1_ENCODE_FUNCTIONS_name(ASN1_BIT_STRING_SEQUENCE, ASN1_BIT_STRING_SEQUENCE)
DECLARE_ASN1_ENCODE_FUNCTIONS_name(ASN1_BIT_STRING_SEQUENCE, X509_COMPOSITE_PUBKEY_SEQUENCE)
DECLARE_ASN1_ENCODE_FUNCTIONS_name(ASN1_BIT_STRING_SEQUENCE, X509_COMPOSITE_SIG_SEQUENCE)

END_C_DECLS

#endif // PKI_OSSL_OCSPROV_H