#include "ocsprov_asn1.h"

// ==============
// ASN1 functions
// ==============

ASN1_ITEM_TEMPLATE(ASN1_BIT_STRING_SEQUENCE) =
        ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_SEQUENCE_OF, 0, ASN1_BIT_STRING_SEQUENCE, ASN1_BIT_STRING)
ASN1_ITEM_TEMPLATE_END(ASN1_BIT_STRING_SEQUENCE)

ASN1_ITEM_TEMPLATE(X509_COMPOSITE_SIG_SEQUENCE) =
        ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_SEQUENCE_OF, 0, X509_COMPOSITE_SIG_SEQUENCE, ASN1_BIT_STRING)
ASN1_ITEM_TEMPLATE_END(X509_COMPOSITE_SIG_SEQUENCE)

ASN1_ITEM_TEMPLATE(X509_COMPOSITE_PUBKEY_SEQUENCE) =
        ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_SEQUENCE_OF, 0, X509_COMPOSITE_PUBKEY_SEQUENCE, ASN1_BIT_STRING)
ASN1_ITEM_TEMPLATE_END(X509_COMPOSITE_PUBKEY_SEQUENCE)

IMPLEMENT_ASN1_ENCODE_FUNCTIONS_fname(ASN1_BIT_STRING_SEQUENCE, ASN1_BIT_STRING_SEQUENCE, ASN1_BIT_STRING_SEQUENCE)
IMPLEMENT_ASN1_ENCODE_FUNCTIONS_fname(ASN1_BIT_STRING_SEQUENCE, X509_COMPOSITE_PUBKEY_SEQUENCE, X509_COMPOSITE_PUBKEY_SEQUENCE)
IMPLEMENT_ASN1_ENCODE_FUNCTIONS_fname(ASN1_BIT_STRING_SEQUENCE, X509_COMPOSITE_SIG_SEQUENCE, X509_COMPOSITE_SIG_SEQUENCE)
