/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2020 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

// #include <openssl/err.h>
// // #include <openssl/composite_err.h>

// #ifndef OPENSSL_NO_ERR

// static const ERR_STRING_DATA COMPOSITE_str_functs[] = {
//     // {ERR_PACK(ERR_LIB_COMPOSITE, EC_F_BN_TO_FELEM, 0), "BN_to_felem"},
//     {0, NULL}
// };

// static const ERR_STRING_DATA COMPOSITE_str_reasons[] = {
//     // {ERR_PACK(ERR_LIB_COMPOSITE, 0, COMPOSITE_R_ASN1_ERROR), "asn1 error"},
//     // {ERR_PACK(ERR_LIB_COMPOSITE, 0, COMPOSITE_R_BAD_SIGNATURE), "bad signature"},
//     // {ERR_PACK(ERR_LIB_COMPOSITE, 0, ECOMPOSITE_R_WRONG_DIGEST), "wrong digest"},
//     // {ERR_PACK(ERR_LIB_COMPOSITE, 0, COMPOSITE_R_WRONG_LENGTH), "wrong length"},
//     // {ERR_PACK(ERR_LIB_COMPOSITE, 0, COMPOSITE_R_WRONG_ORDER), "wrong order"},
//     // {ERR_PACK(ERR_LIB_COMPOSITE, 0, COMPOSITE_R_WRONG_PARAMETERS), "wrong parameters"},
//     {0, NULL}
// };

// #endif

// int ERR_load_COMPOSITE_strings(void)
// {
// #ifndef OPENSSL_NO_ERR
//     // if (ERR_func_error_string(COMPOSITE_str_functs[0].error) == NULL) {
//     //     ERR_load_strings_const(COMPOSITE_str_functs);
//     //     ERR_load_strings_const(COMPOSITE_str_reasons);
//     // }
// #endif
//     return 1;
// }
