/* OID management for libpki */

// Brings in default defs
#include <stdlib.h>
#include <string.h>

#ifndef HEADER_OBJECTS_H
# include <openssl/objects.h>
#endif

#ifndef HEADER_ERR_H
#include <openssl/err.h>
#endif

#ifndef HEADER_OBJECTS_MAC_H
#include <openssl/obj_mac.h>
#endif

#ifndef _LIBPKI_FEATURES_H
#include <libpki/libpki_enables.h>
#endif

#ifndef _LIBPKI_LOG_H
# include <libpki/pki_log.h>
#endif

#ifndef _LIBPKI_OID_DEFS_H
# include <libpki/openssl/pki_oid_defs.h>
#endif

#ifndef _LIBPKI_ERRORS_H
#include <libpki/pki_err.h>
#endif

#ifndef _LIBPKI_OID_H
# include <libpki/pki_oid.h>
#endif

#ifndef _LIBPKI_HSM_MAIN_H
# include <libpki/drivers/hsm_main.h>
#endif

#ifndef _LIBPKI_PKI_X509_ALGOR_H
# include <libpki/pki_algor.h>
#endif

// Default
#ifndef PKI_OK
#define PKI_OK		1
#endif

#ifndef PKI_ERR
#define PKI_ERR		0
#endif

// ==========================
// Data Structure Definitions
// ==========================

typedef struct oid_init_table_st {
	int nid;
	const char * oid;
	const char * name;
	const char * desc;
} OID_INIT_OBJ;

typedef struct sigs_init_table_st {
	int nid;
	const char * oid;
	const char * name;
	const char * desc;
	int hash_nid;
	int pkey_nid;
	const char * pkey_name;
	int sig_nid;
} OID_INIT_SIG;

typedef struct libpki_obj_alias_st {
	int nid;
	const char *name;
	const char *oid;
} LIBPKI_OBJ_ALIAS;

typedef struct obj_alias_st {
	char * oid_new;
	char * oid_current;
} OID_ALIAS;

// =============================
// Objects and Signatures Tables
// =============================

#ifdef ENABLE_ECDSA
static LIBPKI_OBJ_ALIAS nist_curves_alias[] = {
	/* prime field curves */
	{ NID_P192, "P192", "1.2.840.10045.3.1.1" },
	{ NID_P224, "P224", "1.3.132.0.33" },
	{ NID_P256, "P256", "1.2.840.10045.3.1.7" },
	{ NID_P384, "P384", "1.3.132.0.34" },
	{ NID_P521, "P521", "1.3.132.0.35" },

	/* characteristic two field curves */
	{ NID_K163, "K163", "1.3.132.0.1" },
	{ NID_K233, "K233", "1.3.132.0.26" },
	{ NID_K283, "K283", "1.3.132.0.16" },
	{ NID_K409, "K409", "1.3.132.0.36" },
	{ NID_K571, "K571", "1.3.132.0.38" },

	{ NID_B163, "B163", "1.3.132.0.15" },
	{ NID_B233, "B233", "1.3.132.0.27" },
	{ NID_B283, "B283", "1.3.132.0.17" },
	{ NID_B409, "B409", "1.3.132.0.37" },
	{ NID_B571, "B571", "1.3.132.0.39" },

	{ -1, NULL, NULL },
};
#endif

OID_INIT_OBJ oids_table[] = {
	{ 0, OPENCA_OID, OPENCA_NAME, OPENCA_DESC},
	{ 0, CERTIFICATE_TEMPLATE_OID, CERTIFICATE_TEMPLATE_NAME, CERTIFICATE_TEMPLATE_DESC},
	{ 0, LEVEL_OF_ASSURANCE_OID, LEVEL_OF_ASSURANCE_NAME, LEVEL_OF_ASSURANCE_DESC},
	{ 0, CERTIFICATE_USAGE_OID, CERTIFICATE_USAGE_NAME, CERTIFICATE_USAGE_DESC},

#if defined(ENABLE_COMPOSITE)
	// Composite Key - OpenCA OID
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_OID, OPENCA_ALG_PKEY_EXP_COMP_NAME, OPENCA_ALG_PKEY_EXP_COMP_DESC},

	// Composite KEM Explicit - None Defined

#if defined(ENABLE_OQS) || defined(ENABLE_OQSPROV)

	// Explicit Composite Signatures - Dilithium3
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_RSA_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_RSA_SHA256_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_RSA_SHA256_DESC },
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_P256_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_P256_SHA256_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_P256_SHA256_DESC },
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_BRAINPOOL256_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_BRAINPOOL256_SHA256_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_BRAINPOOL256_SHA256_DESC },
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_ED25519_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_ED25519_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_ED25519_DESC },

	// Explicit Composite Signatures - Dilithium5
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_P384_SHA384_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_P384_SHA384_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_P384_SHA384_DESC },
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_BRAINPOOL384_SHA384_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_BRAINPOOL384_SHA384_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_BRAINPOOL384_SHA384_DESC },
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_ED448_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_ED448_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_ED448_DESC },

	// Explicit Composite Signatures - Falcon512
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_P256_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_P256_SHA256_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_P256_SHA256_DESC },
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_BRAINPOOL256_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_BRAINPOOL256_SHA256_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_BRAINPOOL256_SHA256_DESC },
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_ED25519_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_ED25519_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_ED25519_DESC },

	// // Explicit Composite Signatures - Sphincs256
	// { 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_SPHINCS256_P256_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_SPHINCS256_P256_SHA256_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_SPHINCS256_P256_SHA256_DESC },
	// { 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_SPHINCS256_BRAINPOOL256_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_SPHINCS256_BRAINPOOL256_SHA256_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_SPHINCS256_BRAINPOOL256_SHA256_DESC },
	// { 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_SPHINCS256_ED25519_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_SPHINCS256_ED25519_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_SPHINCS256_ED25519_DESC },

	// Explicit Composite Signatures - RSAPSS
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_RSAPSS_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_RSAPSS_SHA256_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_RSAPSS_SHA256_DESC },

	// Explicit Composite Signatures - Non-ID combinations
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_RSA_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_RSA_SHA256_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_RSA_SHA256_DESC },
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_FALCON1024_P521_SHA512_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_FALCON1024_P521_SHA512_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_FALCON1024_P521_SHA512_DESC },
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_FALCON1024_RSA_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_FALCON1024_RSA_SHA256_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_FALCON1024_RSA_SHA256_DESC },
	// { 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_SPHINCS256_RSA_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_SPHINCS256_RSA_SHA256_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_SPHINCS256_RSA_SHA256_DESC },

#endif // End of ENABLE_OQS || ENABLE_OQSPROV
#endif // End of ENABLE_COMPOSITE

#if defined(ENABLE_OQSPROV)

	// PQC Signatures
	{ 0, OPENCA_ALG_PKEY_PQC_DILITHIUM2_OID, OPENCA_ALG_PKEY_PQC_DILITHIUM2_NAME, OPENCA_ALG_PKEY_PQC_DILITHIUM2_DESC },
	{ 0, OPENCA_ALG_PKEY_PQC_DILITHIUM3_OID, OPENCA_ALG_PKEY_PQC_DILITHIUM3_NAME, OPENCA_ALG_PKEY_PQC_DILITHIUM3_DESC },
	{ 0, OPENCA_ALG_PKEY_PQC_DILITHIUM5_OID, OPENCA_ALG_PKEY_PQC_DILITHIUM5_NAME, OPENCA_ALG_PKEY_PQC_DILITHIUM5_DESC },
	{ 0, OPENCA_ALG_PKEY_PQC_FALCON512_OID, OPENCA_ALG_PKEY_PQC_FALCON512_NAME, OPENCA_ALG_PKEY_PQC_FALCON512_DESC },
	{ 0, OPENCA_ALG_PKEY_PQC_FALCON1024_OID, OPENCA_ALG_PKEY_PQC_FALCON1024_NAME, OPENCA_ALG_PKEY_PQC_FALCON1024_DESC },
	{ 0, OPENCA_ALG_PKEY_PQC_SPHINCS128_F_SIMPLE_OID, OPENCA_ALG_PKEY_PQC_SPHINCS128_F_SIMPLE_NAME, OPENCA_ALG_PKEY_PQC_SPHINCS128_F_SIMPLE_DESC },
	{ 0, OPENCA_ALG_PKEY_PQC_SPHINCS192_F_SIMPLE_OID, OPENCA_ALG_PKEY_PQC_SPHINCS192_F_SIMPLE_NAME, OPENCA_ALG_PKEY_PQC_SPHINCS192_F_SIMPLE_DESC },

	// KEMs
	{ 0, OPENCA_ALG_PKEY_PQC_KYBER512_OID, OPENCA_ALG_PKEY_PQC_KYBER512_NAME, OPENCA_ALG_PKEY_PQC_KYBER512_DESC },
	{ 0, OPENCA_ALG_PKEY_PQC_KYBER768_OID, OPENCA_ALG_PKEY_PQC_KYBER768_NAME, OPENCA_ALG_PKEY_PQC_KYBER768_DESC },
	{ 0, OPENCA_ALG_PKEY_PQC_KYBER1024_OID, OPENCA_ALG_PKEY_PQC_KYBER1024_NAME, OPENCA_ALG_PKEY_PQC_KYBER1024_DESC },

#endif


#ifdef ENABLE_COMBINED
	// Alt Key
	{ 0, OPENCA_ALG_PKEY_EXP_ALT_OID, OPENCA_ALG_PKEY_EXP_ALT_NAME, OPENCA_ALG_PKEY_EXP_ALT_DESC},
#endif

#ifdef ENABLE_OQS
	// Experimental
	{ 0, OPENCA_ALG_PKEY_EXP_DILITHIUMX_OID, OPENCA_ALG_PKEY_EXP_DILITHIUMX_NAME, OPENCA_ALG_PKEY_EXP_DILITHIUMX_DESC},
#endif

	{ 0, NULL, NULL, NULL }
};

OID_INIT_SIG sigs_table[] = {

#ifdef ENABLE_COMPOSITE
	// Composite Signatures
	{ 0, OPENCA_ALG_SIGS_COMP_OID, OPENCA_ALG_SIGS_COMP_NAME, OPENCA_ALG_SIGS_COMP_DESC, 0, 0, OPENCA_ALG_PKEY_EXP_COMP_NAME, 0 },
#ifdef ENABLE_SHA1
	{ 0, OPENCA_ALG_SIGS_COMP_SHA1_OID, OPENCA_ALG_SIGS_COMP_SHA1_NAME, OPENCA_ALG_SIGS_COMP_SHA1_DESC, NID_sha1, 0, OPENCA_ALG_PKEY_EXP_COMP_NAME, 0 },
#endif
#ifdef ENABLE_SHA2
	{ 0, OPENCA_ALG_SIGS_COMP_SHA256_OID, OPENCA_ALG_SIGS_COMP_SHA256_NAME, OPENCA_ALG_SIGS_COMP_SHA256_DESC, NID_sha256, 0, OPENCA_ALG_PKEY_EXP_COMP_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_COMP_SHA384_OID, OPENCA_ALG_SIGS_COMP_SHA384_NAME, OPENCA_ALG_SIGS_COMP_SHA384_DESC, NID_sha384, 0, OPENCA_ALG_PKEY_EXP_COMP_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_COMP_SHA512_OID, OPENCA_ALG_SIGS_COMP_SHA512_NAME, OPENCA_ALG_SIGS_COMP_SHA512_DESC, NID_sha512, 0, OPENCA_ALG_PKEY_EXP_COMP_NAME, 0 },
#endif
#ifdef ENABLE_SHA3
	{ 0, OPENCA_ALG_SIGS_COMP_SHA3_256_OID, OPENCA_ALG_SIGS_COMP_SHA3_256_NAME, OPENCA_ALG_SIGS_COMP_SHA3_256_DESC, NID_sha3_256, 0, OPENCA_ALG_PKEY_EXP_COMP_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_COMP_SHA3_384_OID, OPENCA_ALG_SIGS_COMP_SHA3_384_NAME, OPENCA_ALG_SIGS_COMP_SHA3_384_DESC, NID_sha3_384, 0, OPENCA_ALG_PKEY_EXP_COMP_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_COMP_SHA3_512_OID, OPENCA_ALG_SIGS_COMP_SHA3_512_NAME, OPENCA_ALG_SIGS_COMP_SHA3_512_DESC, NID_sha3_512, 0, OPENCA_ALG_PKEY_EXP_COMP_NAME, 0 },
#endif
#ifdef ENABLE_SHAKE
	// { 0, OPENCA_ALG_SIGS_COMP_SHAKE128_OID, OPENCA_ALG_SIGS_COMP_SHAKE128_NAME, OPENCA_ALG_SIGS_COMP_SHAKE128_DESC, NID_shake128, 0, OPENCA_ALG_PKEY_EXP_COMP_NAME, 0 },
	// { 0, OPENCA_ALG_SIGS_COMP_SHAKE256_OID, OPENCA_ALG_SIGS_COMP_SHAKE256_NAME, OPENCA_ALG_SIGS_COMP_SHAKE256_DESC, NID_shake128, 0, OPENCA_ALG_PKEY_EXP_COMP_NAME, 0 },
#endif
#endif

#ifdef ENABLE_COMBINED
	// Alternative Signatures
	{ 0, OPENCA_ALG_SIGS_ALT_OID, OPENCA_ALG_SIGS_ALT_NAME, OPENCA_ALG_SIGS_ALT_DESC, 0, 0, OPENCA_ALG_PKEY_EXP_ALT_NAME, 0 },
#ifdef ENABLE_SHA1
	{ 0, OPENCA_ALG_SIGS_ALT_SHA1_OID, OPENCA_ALG_SIGS_ALT_SHA1_NAME, OPENCA_ALG_SIGS_ALT_SHA1_DESC, NID_sha1, 0, OPENCA_ALG_PKEY_EXP_ALT_NAME, 0 },
#endif
#ifdef ENABLE_SHA2
	{ 0, OPENCA_ALG_SIGS_ALT_SHA256_OID, OPENCA_ALG_SIGS_ALT_SHA256_NAME, OPENCA_ALG_SIGS_ALT_SHA256_DESC, NID_sha256, 0, OPENCA_ALG_PKEY_EXP_ALT_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_ALT_SHA384_OID, OPENCA_ALG_SIGS_ALT_SHA384_NAME, OPENCA_ALG_SIGS_ALT_SHA384_DESC, NID_sha384, 0, OPENCA_ALG_PKEY_EXP_ALT_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_ALT_SHA512_OID, OPENCA_ALG_SIGS_ALT_SHA512_NAME, OPENCA_ALG_SIGS_ALT_SHA512_DESC, NID_sha512, 0, OPENCA_ALG_PKEY_EXP_ALT_NAME, 0 },
#endif
#ifdef ENABLE_SHA3
	{ 0, OPENCA_ALG_SIGS_ALT_SHA3_256_OID, OPENCA_ALG_SIGS_ALT_SHA3_256_NAME, OPENCA_ALG_SIGS_ALT_SHA3_256_DESC, NID_sha3_256, 0, OPENCA_ALG_PKEY_EXP_ALT_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_ALT_SHA3_384_OID, OPENCA_ALG_SIGS_ALT_SHA3_384_NAME, OPENCA_ALG_SIGS_ALT_SHA3_384_DESC, NID_sha3_384, 0, OPENCA_ALG_PKEY_EXP_ALT_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_ALT_SHA3_512_OID, OPENCA_ALG_SIGS_ALT_SHA3_512_NAME, OPENCA_ALG_SIGS_ALT_SHA3_512_DESC, NID_sha3_512, 0, OPENCA_ALG_PKEY_EXP_ALT_NAME, 0 },
#endif
#ifdef ENABLE_SHAKE
	{ 0, OPENCA_ALG_SIGS_ALT_SHAKE128_OID, OPENCA_ALG_SIGS_ALT_SHAKE128_NAME, OPENCA_ALG_SIGS_ALT_SHAKE128_DESC, NID_shake128, 0, OPENCA_ALG_PKEY_EXP_ALT_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_ALT_SHAKE256_OID, OPENCA_ALG_SIGS_ALT_SHAKE256_NAME, OPENCA_ALG_SIGS_ALT_SHAKE256_DESC, NID_shake128, 0, OPENCA_ALG_PKEY_EXP_ALT_NAME, 0 },
#endif
#endif

#if defined(ENABLE_OQS) || defined(ENABLE_OQSPROV)

	// Dilithium2 Signatures
	// { 0, OPENCA_ALG_SIGS_PQC_DILITHIUM2_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM2_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM2_DESC, NID_undef, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM2_NAME, 0 },
#ifdef ENABLE_SHA2
	{ 0, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHA256_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHA256_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHA256_DESC, NID_sha256, 0, OPENCA_ALG_PKEY_PQC_DILITHIUM2_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHA384_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHA384_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHA384_DESC, NID_sha384, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM2_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHA512_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHA512_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHA512_DESC, NID_sha512, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM2_NAME, 0 },
#endif

#ifdef ENABLE_SHA3
	{ 0, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHA3_256_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHA3_256_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHA3_256_DESC, NID_sha3_256, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM2_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHA3_384_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHA3_384_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHA3_384_DESC, NID_sha3_384, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM2_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHA3_512_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHA3_512_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHA3_512_DESC, NID_sha3_512, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM2_NAME, 0 },
#endif

#ifdef ENABLE_SHAKE
	// { 0, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHAKE128_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHAKE128_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHAKE128_DESC, NID_shake128, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM2_NAME, 0 },
	// { 0, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHAKE256_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHAKE256_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM2_SHAKE256_DESC, NID_shake256, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM2_NAME, 0 },
#endif
	
	// Dilithium3 Signatures
	// { 0, OPENCA_ALG_SIGS_PQC_DILITHIUM3_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM3_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM3_DESC, NID_undef, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM3_NAME, 0 },
#ifdef ENABLE_SHA2
	{ 0, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHA256_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHA256_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHA256_DESC, NID_sha256, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM3_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHA384_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHA384_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHA384_DESC, NID_sha384, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM3_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHA512_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHA512_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHA512_DESC, NID_sha512, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM3_NAME, 0 },
#endif
#ifdef ENABLE_SHA3
	{ 0, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHA3_256_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHA3_256_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHA3_256_DESC, NID_sha3_256, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM3_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHA3_384_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHA3_384_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHA3_384_DESC, NID_sha3_384, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM3_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHA3_512_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHA3_512_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHA3_512_DESC, NID_sha3_512, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM3_NAME, 0 },
#endif
#ifdef ENABLE_SHAKE
	// { 0, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHAKE128_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHAKE128_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHAKE128_DESC, NID_shake128, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM3_NAME, 0 },
	// { 0, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHAKE256_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHAKE256_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM3_SHAKE256_DESC, NID_shake256, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM3_NAME, 0 },
#endif

	// Dilithium5 Signatures
	// { 0, OPENCA_ALG_SIGS_PQC_DILITHIUM5_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM5_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM5_DESC, NID_undef, NID_dilithium5, 0 },
#ifdef ENABLE_SHA2
	{ 0, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHA256_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHA256_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHA256_DESC, NID_sha256, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM5_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHA384_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHA384_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHA384_DESC, NID_sha384, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM5_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHA512_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHA512_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHA512_DESC, NID_sha512, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM5_NAME, 0 },
#endif
#ifdef ENABLE_SHA3
	{ 0, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHA3_256_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHA3_256_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHA3_256_DESC, NID_sha3_256, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM5_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHA3_384_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHA3_384_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHA3_384_DESC, NID_sha3_384, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM5_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHA3_512_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHA3_512_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHA3_512_DESC, NID_sha3_512, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM5_NAME, 0 },
#endif
#ifdef ENABLE_SHAKE
	// { 0, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHAKE128_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHAKE128_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHAKE128_DESC, NID_shake128, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM5_NAME, 0 },
	// { 0, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHAKE256_OID, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHAKE256_NAME, OPENCA_ALG_SIGS_PQC_DILITHIUM5_SHAKE256_DESC, NID_shake256, NID_undef, OPENCA_ALG_PKEY_PQC_DILITHIUM5_NAME, 0 },
#endif

	// // Experimental - DilithiumX3
	// // { 0, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_OID, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_NAME, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_DESC, NID_undef, 0, 0 },
	// { 0, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHA256_OID, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHA256_NAME, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHA256_DESC, NID_sha256, 0, 0 },
	// { 0, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHA384_OID, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHA384_NAME, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHA384_DESC, NID_sha384, 0, 0 },
	// { 0, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHA512_OID, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHA512_NAME, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHA512_DESC, NID_sha512, 0, 0 },
	// { 0, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHA3_256_OID, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHA3_256_NAME, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHA3_256_DESC, NID_sha3_256, 0, 0 },
	// { 0, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHA3_384_OID, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHA3_384_NAME, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHA3_384_DESC, NID_sha3_384, 0, 0 },
	// { 0, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHA3_512_OID, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHA3_512_NAME, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHA3_512_DESC, NID_sha3_512, 0, 0 },
	// { 0, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHAKE128_OID, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHAKE128_NAME, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHAKE128_DESC, NID_shake128, 0, 0 },
	// { 0, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHAKE256_OID, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHAKE256_NAME, OPENCA_ALG_SIGS_EXP_DILITHIUMX3_SHAKE256_DESC, NID_shake256, 0, 0 },

	// Falcon512 Signatures
	// { 0, OPENCA_ALG_SIGS_PQC_FALCON512_OID, OPENCA_ALG_SIGS_PQC_FALCON512_NAME, OPENCA_ALG_SIGS_PQC_FALCON512_DESC, NID_undef, NID_falcon512, 0 },
#ifdef ENABLE_SHA2
	{ 0, OPENCA_ALG_SIGS_PQC_FALCON512_SHA256_OID, OPENCA_ALG_SIGS_PQC_FALCON512_SHA256_NAME, OPENCA_ALG_SIGS_PQC_FALCON512_SHA256_DESC, NID_sha256, NID_undef, OPENCA_ALG_PKEY_PQC_FALCON512_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_PQC_FALCON512_SHA384_OID, OPENCA_ALG_SIGS_PQC_FALCON512_SHA384_NAME, OPENCA_ALG_SIGS_PQC_FALCON512_SHA384_DESC, NID_sha384, NID_undef, OPENCA_ALG_PKEY_PQC_FALCON512_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_PQC_FALCON512_SHA512_OID, OPENCA_ALG_SIGS_PQC_FALCON512_SHA512_NAME, OPENCA_ALG_SIGS_PQC_FALCON512_SHA512_DESC, NID_sha512, NID_undef, OPENCA_ALG_PKEY_PQC_FALCON512_NAME, 0 },
#endif
#ifdef ENABLE_SHA3
	{ 0, OPENCA_ALG_SIGS_PQC_FALCON512_SHA3_256_OID, OPENCA_ALG_SIGS_PQC_FALCON512_SHA3_256_NAME, OPENCA_ALG_SIGS_PQC_FALCON512_SHA3_256_DESC, NID_sha3_256, NID_undef, OPENCA_ALG_PKEY_PQC_FALCON512_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_PQC_FALCON512_SHA3_384_OID, OPENCA_ALG_SIGS_PQC_FALCON512_SHA3_384_NAME, OPENCA_ALG_SIGS_PQC_FALCON512_SHA3_384_DESC, NID_sha3_384, NID_undef, OPENCA_ALG_PKEY_PQC_FALCON512_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_PQC_FALCON512_SHA3_512_OID, OPENCA_ALG_SIGS_PQC_FALCON512_SHA3_512_NAME, OPENCA_ALG_SIGS_PQC_FALCON512_SHA3_512_DESC, NID_sha3_512, NID_undef, OPENCA_ALG_PKEY_PQC_FALCON512_NAME, 0 },
#endif
#ifdef ENABLE_SHAKE
	// { 0, OPENCA_ALG_SIGS_PQC_FALCON512_SHAKE128_OID, OPENCA_ALG_SIGS_PQC_FALCON512_SHAKE128_NAME, OPENCA_ALG_SIGS_PQC_FALCON512_SHAKE128_DESC, NID_shake128, NID_undef, OPENCA_ALG_PKEY_PQC_FALCON512_NAME, 0 },
	// { 0, OPENCA_ALG_SIGS_PQC_FALCON512_SHAKE256_OID, OPENCA_ALG_SIGS_PQC_FALCON512_SHAKE256_NAME, OPENCA_ALG_SIGS_PQC_FALCON512_SHAKE256_DESC, NID_shake256, NID_undef, OPENCA_ALG_PKEY_PQC_FALCON512_NAME, 0 },
#endif

	// Falcon1024 Signatures
	// { 0, OPENCA_ALG_SIGS_PQC_FALCON1024_OID, OPENCA_ALG_SIGS_PQC_FALCON1024_NAME, OPENCA_ALG_SIGS_PQC_FALCON1024_DESC, NID_undef, NID_falcon1024, 0 },
#ifdef ENABLE_SHA2
	{ 0, OPENCA_ALG_SIGS_PQC_FALCON1024_SHA256_OID, OPENCA_ALG_SIGS_PQC_FALCON1024_SHA256_NAME, OPENCA_ALG_SIGS_PQC_FALCON1024_SHA256_DESC, NID_sha256, NID_undef, OPENCA_ALG_PKEY_PQC_FALCON1024_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_PQC_FALCON1024_SHA384_OID, OPENCA_ALG_SIGS_PQC_FALCON1024_SHA384_NAME, OPENCA_ALG_SIGS_PQC_FALCON1024_SHA384_DESC, NID_sha384, NID_undef, OPENCA_ALG_PKEY_PQC_FALCON1024_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_PQC_FALCON1024_SHA512_OID, OPENCA_ALG_SIGS_PQC_FALCON1024_SHA512_NAME, OPENCA_ALG_SIGS_PQC_FALCON1024_SHA512_DESC, NID_sha512, NID_undef, OPENCA_ALG_PKEY_PQC_FALCON1024_NAME, 0 },
#endif
#ifdef ENABLE_SHA3
	{ 0, OPENCA_ALG_SIGS_PQC_FALCON1024_SHA3_256_OID, OPENCA_ALG_SIGS_PQC_FALCON1024_SHA3_256_NAME, OPENCA_ALG_SIGS_PQC_FALCON1024_SHA3_256_DESC, NID_sha3_256, NID_undef, OPENCA_ALG_PKEY_PQC_FALCON1024_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_PQC_FALCON1024_SHA3_384_OID, OPENCA_ALG_SIGS_PQC_FALCON1024_SHA3_384_NAME, OPENCA_ALG_SIGS_PQC_FALCON1024_SHA3_384_DESC, NID_sha3_384, NID_undef, OPENCA_ALG_PKEY_PQC_FALCON1024_NAME, 0 },
	{ 0, OPENCA_ALG_SIGS_PQC_FALCON1024_SHA3_512_OID, OPENCA_ALG_SIGS_PQC_FALCON1024_SHA3_512_NAME, OPENCA_ALG_SIGS_PQC_FALCON1024_SHA3_512_DESC, NID_sha3_512, NID_undef, OPENCA_ALG_PKEY_PQC_FALCON1024_NAME, 0 },
#endif
#ifdef ENABLE_SHAKE
	// { 0, OPENCA_ALG_SIGS_PQC_FALCON1024_SHAKE128_OID, OPENCA_ALG_SIGS_PQC_FALCON1024_SHAKE128_NAME, OPENCA_ALG_SIGS_PQC_FALCON1024_SHAKE128_DESC, NID_shake128, NID_undef, OPENCA_ALG_PKEY_PQC_FALCON1024_NAME, 0 },
	// { 0, OPENCA_ALG_SIGS_PQC_FALCON1024_SHAKE256_OID, OPENCA_ALG_SIGS_PQC_FALCON1024_SHAKE256_NAME, OPENCA_ALG_SIGS_PQC_FALCON1024_SHAKE256_DESC, NID_shake256, NID_undef, OPENCA_ALG_PKEY_PQC_FALCON1024_NAME, 0 },
#endif

	// Sphincs+ 128f Signatures
	{ 0, OPENCA_ALG_SIGS_PQC_SPHINCS128_F_SIMPLE_OID, OPENCA_ALG_SIGS_PQC_SPHINCS128_F_SIMPLE_NAME, OPENCA_ALG_SIGS_PQC_SPHINCS128_F_SIMPLE_DESC, NID_undef, NID_undef, OPENCA_ALG_PKEY_PQC_SPHINCS128_F_SIMPLE_NAME, 0 },

	// Sphincs+ 192f Signatures
	{ 0, OPENCA_ALG_SIGS_PQC_SPHINCS192_F_SIMPLE_OID, OPENCA_ALG_SIGS_PQC_SPHINCS192_F_SIMPLE_NAME, OPENCA_ALG_SIGS_PQC_SPHINCS192_F_SIMPLE_DESC, NID_undef, NID_undef, OPENCA_ALG_PKEY_PQC_SPHINCS192_F_SIMPLE_NAME, 0 },

	// Explicit Composite Signatures

#if defined(ENABLE_COMPOSITE)

#ifdef ENABLE_SHA2

	// Explicit Composite Signatures - Dilithium3
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_RSA_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_RSA_SHA256_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_RSA_SHA256_DESC, NID_undef, NID_undef, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_RSA_SHA256_OID, 0 },
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_P256_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_P256_SHA256_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_P256_SHA256_DESC, NID_undef, NID_undef, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_P256_SHA256_NAME, 0 },
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_BRAINPOOL256_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_BRAINPOOL256_SHA256_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_BRAINPOOL256_SHA256_DESC, NID_undef, NID_undef, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_BRAINPOOL256_SHA256_NAME, 0 },
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_ED25519_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_ED25519_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_ED25519_DESC, NID_undef, NID_undef, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_ED25519_NAME, 0 },

	// Explicit Composite Signatures - Dilithium5
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_P384_SHA384_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_P384_SHA384_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_P384_SHA384_DESC, NID_undef, NID_undef, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_P384_SHA384_NAME, 0 },
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_BRAINPOOL384_SHA384_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_BRAINPOOL384_SHA384_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_BRAINPOOL384_SHA384_DESC, NID_undef, NID_undef, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_BRAINPOOL384_SHA384_NAME, 0 },
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_ED448_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_ED448_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_ED448_DESC, NID_undef, NID_undef, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_ED448_NAME, 0 },

	// Explicit Composite Signatures - Falcon512
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_P256_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_P256_SHA256_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_P256_SHA256_DESC, NID_undef, NID_undef, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_P256_SHA256_NAME, 0 },
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_BRAINPOOL256_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_BRAINPOOL256_SHA256_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_BRAINPOOL256_SHA256_DESC, NID_undef, NID_undef, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_BRAINPOOL256_SHA256_NAME, 0 },
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_ED25519_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_ED25519_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_ED25519_DESC, NID_undef, NID_undef, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_ED25519_NAME, 0 },

	// Explicit Composite Signatures - RSAPSS
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_RSAPSS_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_RSAPSS_SHA256_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_RSAPSS_SHA256_DESC, NID_undef, NID_undef, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_RSAPSS_SHA256_NAME, 0 },

	// Explicit Composite Signatures - Non-ID combinations
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_RSA_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_RSA_SHA256_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_RSA_SHA256_DESC, NID_undef, NID_undef, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_RSA_SHA256_NAME, 0 },
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_FALCON1024_P521_SHA512_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_FALCON1024_P521_SHA512_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_FALCON1024_P521_SHA512_DESC, NID_undef, NID_undef, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_FALCON1024_P521_SHA512_NAME, 0 },
	{ 0, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_FALCON1024_RSA_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_FALCON1024_RSA_SHA256_NAME, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_FALCON1024_RSA_SHA256_DESC, NID_undef, NID_undef, OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_FALCON1024_RSA_SHA256_NAME, 0 },

#endif // End of ENABLE_SHA2
#endif // End of ENABLE_COMPOSITE
#endif // End of ENABLE_OQS || ENABLE_OQSPROV

	{ 0, NULL, NULL, NULL, 0, 0, NULL, 0 }
};

OID_ALIAS alias_table[] = {
	// { nid, oid, alias_oid }
	// Entrust (to) <- LibPKI (from) 
	// { ALIAS OID, EXISTING OID }

	// // Explicit: Dilithium3-RSA-PKCS15
	// { OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_RSA_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_OID },
	// // Explicit: Dilithium3-P256
	// { OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_P256_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_OID },
	// // Explicit: Dilithium3-BrainpoolP256r1
	// { OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_BRAINPOOL256_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_OID},
	// // Explicit: Dilithium3-Ed25519
	// { OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_ED25519_OID, OPENCA_ALG_PKEY_EXP_COMP_OID },
	// // Explicit: Dilithium5-P384
	// { OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_P384_SHA384_OID, OPENCA_ALG_PKEY_EXP_COMP_OID },
	// // Explicit: Dilithium5-BrainpoolP384r1
	// { OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_BRAINPOOL384_SHA384_OID, OPENCA_ALG_PKEY_EXP_COMP_OID },
	// // Explicit: Dilithium5-Ed25519
	// { OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_ED448_OID, OPENCA_ALG_PKEY_EXP_COMP_OID },
	// // Explicit: Falcon512-P256
	// { OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_P256_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_OID },
	// // Explicit: Falcon512-BrainpoolP256r1
	// { OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_BRAINPOOL256_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_OID },
	// // Explicit: Falcon512-ED25519
	// { OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_ED25519_OID, OPENCA_ALG_PKEY_EXP_COMP_OID },
	// // Explicit: Sphincs-P256
	// { OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_SPHINCS256_P256_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_OID },
	// // Explicit: Sphincs-BrainpoolP256r1
	// { OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_SPHINCS256_BRAINPOOL256_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_OID },
	// // Explicit: Sphincs-Ed25519
	// { OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_SPHINCS256_ED25519_OID, OPENCA_ALG_PKEY_EXP_COMP_OID },
	// // Explicit: Dilithium3-RSAPSS
	// { OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM3_RSAPSS_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_OID },

	// // -------------------- Non-Standard Explicit Combinations ------------------- //

	// // Explicit: Falcon512-RSA
	// { OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_FALCON512_RSA_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_OID },
	// // Explicit: Dilithium5-Falcon1024-P521
	// { OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_FALCON1024_P521_SHA512_OID, OPENCA_ALG_PKEY_EXP_COMP_OID },
	// // Explicit: Dilithium5-Falcon1024-RSA
	// { OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_DILITHIUM5_FALCON1024_RSA_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_OID },
	// // Explicit: Sphincs-RSA
	// { OPENCA_ALG_PKEY_EXP_COMP_EXPLICIT_SPHINCS256_RSA_SHA256_OID, OPENCA_ALG_PKEY_EXP_COMP_OID  },

	// ----------------------------- End of the list ----------------------------- //

	{ NULL, NULL }
};

// ================
// Static Functions
// ================

static int __create_object_with_id (const char * oid, 
									const char * sn, 
									const char * ln,
									int 		 id) {
	int ret = PKI_OK;
	unsigned char *buf;
	int i;

	ASN1_OBJECT *obj=NULL;

	// Create a NEW ID
	if (id < 0) id = OBJ_new_nid(1);

	// Gets the allocation for the object
    if ((i = a2d_ASN1_OBJECT(NULL,0,oid,-1)) <= 0 )
		return PKI_ERR;

	// Allocates the needed buffer memory
    if ((buf=(unsigned char *)OPENSSL_malloc((size_t)i)) == NULL) 
		return PKI_ERR;

	// Generates the Object
    if ((i=a2d_ASN1_OBJECT(buf,i,oid,-1)) == 0 )
		goto err;

    if ((obj = (ASN1_OBJECT *)ASN1_OBJECT_create(id,buf,i,sn,ln)) == 0)
        goto err;

	// All Done, return the object
    ret = OBJ_add_object(obj);

err:
    ASN1_OBJECT_free(obj);
    OPENSSL_free(buf);

	if( ret == 0 ) return PKI_ERR;

	return PKI_OK;
}

// ==============
// Main Functions
// ==============

int PKI_X509_OID_init() {

	OID_INIT_SIG * sig = sigs_table;
	int index = 0;

#ifdef ENABLE_ECDSA

	for (int i = 0; nist_curves_alias[i].name; i++ ) {
		PKI_OID *oid = NULL;
		char buf[2048];

		if( nist_curves_alias[i].oid ) {
			oid = PKI_OID_get( (char *) nist_curves_alias[i].oid );
		} else {
			oid = PKI_OID_new_id( nist_curves_alias[i].nid );
		}
		
		if (!oid) continue;

		OBJ_obj2txt(buf, sizeof(buf), oid, 1);
		PKI_OID_free ( oid );

		if( __create_object_with_id (buf,
									 nist_curves_alias[i].name, 
									 nist_curves_alias[i].name, 
									 nist_curves_alias[i].nid ) == 0 ) {
				// Error while adding "easy" names for NIST curves
				PKI_DEBUG("Cannot add NIST curve alias %s", nist_curves_alias[i].name);
		}
	}

#endif

	// Process all the objects/items
	OID_INIT_OBJ * obj = oids_table;
	while (obj != NULL && obj->oid != NULL) {

		// Checks if the OID already exists
		if (OBJ_txt2nid(obj->oid) != NID_undef) {
			// PKI_DEBUG("OID value (%s) is already defined as %s (%s), skipping",
			// 	obj->oid, OBJ_nid2sn(OBJ_txt2nid(obj->oid)), OBJ_nid2ln(OBJ_txt2nid(obj->oid)));
			obj = &oids_table[++index];
			continue;
		}

		// Checks if the OID already exists
		if ((obj->nid = OBJ_txt2nid(obj->name)) != NID_undef) {
			// PKI_DEBUG("OID Name (%s) is already defined as %s (%s), skipping",
			// 	obj->name, OBJ_nid2sn(OBJ_txt2nid(obj->name)), OBJ_nid2ln(OBJ_txt2nid(obj->name)));
			obj = &oids_table[++index];
			continue;
		}

		// Resets the Error
		ERR_clear_error();

		// Generate the object
		obj->nid = OBJ_create(obj->oid, obj->name, obj->desc);

		// PKI_DEBUG("Creating New OID %s (%s) with id %d (%s)", i
		// 		obj->oid, obj->name, obj->nid, obj->desc);

		// Verify the results
		if (obj->nid == 0) {
			size_t err_number = HSM_get_errno(NULL);
			PKI_DEBUG("[1] Cannot create NID for %s (%s) (Crypto Error: %s)", 
				obj->name, obj->oid, HSM_get_errdesc(err_number, NULL));
			fflush(stderr);
		}

		// Generate the name object
		OBJ_create(obj->name, obj->oid, obj->desc);

		// PKI_DEBUG("Creating New OID %s (%s) with id %d (%s)", i
		// 		obj->oid, obj->name, obj->nid, obj->desc);

		// Verify the results
		if (obj->nid == 0) {
			size_t err_number = HSM_get_errno(NULL);
			PKI_DEBUG("[2] Cannot create NID for %s (%s) (Crypto Error: %s)", 
				obj->name, obj->oid, HSM_get_errdesc(err_number, NULL));
			fflush(stderr);
		}

		// Next Entry
		obj = &oids_table[++index];
	}

	// Resets the index
	index = 0;
	sig = sigs_table;

	// Process all the signatures
	while (sig != NULL && sig->oid != NULL) {

		// Tests the result
		int test_sigid = -1;
		int test_digest_nid = -1;
		int test_pkey_nid = -1;

		// PKI_DEBUG("Adding Signature OID %s (%s) with PKEY id %d (%s)", sig->oid, sig->name, sig->pkey_nid, sig->pkey_name);

		// Checks if we need to get the OID of the PKEY
		if (sig->pkey_nid == NID_undef) {

			// PKI_DEBUG("Config for %s (%s) has no PKEY OID (%d), trying to get it from the pkey_oid/name (%s)", 
			// 	sig->oid, sig->name, sig->pkey_nid, sig->pkey_name);

			if ((sig->pkey_nid = OBJ_txt2nid(sig->pkey_name)) == NID_undef) {
				PKI_DEBUG("Cannot get PKEY OID for %s (pkey_name: %s)", sig->oid, sig->pkey_name);
			}
		}

		// PKI_DEBUG("Using PKEY OID (pkey_name: %s, pkey_nid: %d)", sig->pkey_name, sig->pkey_nid);
		// PKI_DEBUG("Determining if to create the signature OID for %s (%s)", sig->name, sig->oid);

		// Checks if the object already exists
		if ((sig->sig_nid = OBJ_txt2nid(sig->oid)) == NID_undef) {
			// Generates the New Signature Object
			sig->sig_nid = OBJ_create(sig->oid, sig->name, sig->desc);
			if (sig->sig_nid == NID_undef) {
				// Error Condition, nothing to do here
				PKI_ERROR(PKI_ERR_ALGOR_SET, NULL);
			}
		}
		
		test_sigid = -1;
		if (!OBJ_find_sigid_by_algs(&test_sigid, sig->hash_nid, sig->pkey_nid || test_sigid == NID_undef) ) {
			
			// PKI_DEBUG("Got New OID for the Signature %s (%d)", sig->name, sig->sig_nid);
			PKI_DEBUG("Adding signature (%s) with ID (%d), Hash ID (%d), and Pkey ID (%d)", 
				sig->name, sig->sig_nid, sig->hash_nid, sig->pkey_nid);

			// Adds the Signature NID to the OpenSSL's Index (and our table)
			if (!OBJ_add_sigid(sig->sig_nid, sig->hash_nid, sig->pkey_nid)) {
				PKI_DEBUG("Cannot associate signature nid (%d) with hash nid (%d) and pkey nid (%d)",
					sig->sig_nid, sig->hash_nid, sig->pkey_nid);
			}

			// Checks we have gotten the algorithm added
			test_sigid = -1;
			if (!OBJ_find_sigid_by_algs(&test_sigid, sig->hash_nid,  sig->pkey_nid)) {
				PKI_DEBUG("Cannot find the newly added algorithm (should be: %d, found: %d) from hash nid (%d) and pkey nid (%d)",
					sig->sig_nid, test_sigid, sig->hash_nid,  sig->pkey_nid);
			}

		} else {

			// PKI_DEBUG("Found Signature OID %s (%d) with PKEY id %d (%s) and DIGEST id %d (%s)", 
			// 	sig->name, sig->nid, sig->pkey_nid, sig->pkey_name, sig->hash_nid, EVP_MD_name(EVP_get_digestbynid(sig->hash_nid)));
			// Adds the Signature NID to the OpenSSL's Index (and our table)
			if (test_sigid <= 0 && !OBJ_add_sigid(sig->sig_nid, sig->hash_nid, sig->pkey_nid)) {
				PKI_DEBUG("[2] Cannot associate signature nid (%d) with hash nid (%d) and pkey nid (%d)",
					sig->sig_nid, sig->hash_nid, sig->pkey_nid);
			}
		}

		test_digest_nid = 0;
		test_pkey_nid = 0;
		if (!OBJ_find_sigid_algs(sig->sig_nid, &test_digest_nid, &test_pkey_nid)) {
			PKI_DEBUG("Cannot decouple hash nid (%d) and pkey nid (%d) from the signature nid (%d)",
				test_digest_nid, test_pkey_nid, sig->sig_nid);
		}

		sig = &sigs_table[++index];
	}

	// Resets the index
	index = 0;
	OID_ALIAS * alias = alias_table;
	alias = &alias_table[index];

	// Process all the aliases
	while (alias != NULL && alias->oid_new != NULL && alias->oid_current != NULL) {

		int from = -1, to = -1;
			// Identifiers for the OIDs

		// Resets the Crypto Layer Error
		ERR_clear_error();

		// Gets the NIDs we need
		from = OBJ_txt2nid(alias->oid_new);
		to = OBJ_txt2nid(alias->oid_current);

		// Checks the NIDs
		if (from == NID_undef || to == NID_undef) {
			PKI_DEBUG("(%d) Cannot add a new alias %s (%s) for the existing %s (%s). Either the new (%d) or the existing (%d) OIDs are not defined (Crypto Error: %s)", 
				index, OBJ_nid2sn(OBJ_txt2nid(alias->oid_new)), alias->oid_new, OBJ_nid2sn(OBJ_txt2nid(alias->oid_current)), alias->oid_current,
				from, to, HSM_get_errdesc(HSM_get_errno(NULL), NULL));
			alias = &alias_table[++index];
			continue;
		}

		// Creates the alias
		if (!EVP_PKEY_asn1_add_alias(to, from)) {
			PKI_DEBUG("(%d) Cannot add Alias (%s) for Algorithm (%s) (Crypto Error: %s)", 
				index, alias->oid_new, alias->oid_current, HSM_get_errdesc(HSM_get_errno(NULL), NULL));
			alias = &alias_table[++index];
			continue;
		}

		// PKI_DEBUG("(%d) Created New OID Alias (%s) %s -> %s (%s)", 
		// 	index, OBJ_nid2sn(OBJ_txt2nid(alias->oid_new)), alias->oid_new,
		// 	OBJ_nid2sn(OBJ_txt2nid(alias->oid_current)), alias->oid_current);

		// Advances the index
		alias = &alias_table[++index];
	}

	PKI_DEBUG("===== BEGIN: Extra Experimental OID stuff for DEBUGGING =====");

	// PKI_OID * pkey_obj = PKI_OID_new_text(OPENCA_ALG_PKEY_EXP_COMP_NAME);
	// int pkey_obj_id = PKI_OID_get_id(pkey_obj);
	// PKI_OID * sig_obj = PKI_OID_new_text(OPENCA_ALG_SIGS_COMP_SHA256_NAME);
	// int sig_obj_id = PKI_OID_get_id(sig_obj);

	// // PKI_DIGEST_ALG * digest = PKI_DIGEST_ALG_SHA256;
	PKI_DIGEST_ALG * digest = PKI_DIGEST_ALG_SHA256;

	PKI_ID digest_id = EVP_MD_get_type(digest);

	// int success = OBJ_add_sigid(sig_obj_id, digest_id, pkey_obj_id);
	// PKI_DEBUG("Added (success: %d) New Signing Algorithm (%s) with ID (%d), Hash ID (%d), and Pkey ID (%d)", 
	// 	success, OPENCA_ALG_SIGS_COMP_SHA256_NAME, sig_obj_id, digest_id, pkey_obj_id);

	int test_digest_nid = 0;
	int test_pkey_nid = 0;
	int test_sig_nid = 0;
	// success = OBJ_find_sigid_algs(sig_obj_id, &test_digest_nid, &test_pkey_nid);
	// PKI_DEBUG("Retrieved (success: %d) Digest ID (%d), and Pkey ID (%d)", 
	// 	success, test_digest_nid, test_pkey_nid);
	// success = OBJ_find_sigid_by_algs(&test_sig_nid, test_digest_nid, test_pkey_nid);
	// PKI_DEBUG("Retrieved (success: %d) New Signing Algorithm (%s) ID (%d), Hash ID (%d), and Pkey ID (%d)", 
	// 	success, OPENCA_ALG_SIGS_COMP_SHA256_NAME, test_sig_nid, test_digest_nid, test_pkey_nid);

	int success = OBJ_create("1.2.3.4.5.6", "TEST-KEY-OID", "TEST-KEY-OID");
	if (!success) {
		PKI_DEBUG("Cannot create new OID for TEST-KEY-OID");
	} else {
		PKI_DEBUG("Created new OID for TEST-KEY-OID");
		success = OBJ_create("1.2.3.4.5.6.7", "TEST-SIG-OID", "TEST-SIG-OID");
		if (!success) {
			PKI_DEBUG("Cannot create new OID for TEST-SIG-OID");
		} else {
			PKI_DEBUG("Created new OID for TEST-SIG-OID");
			// test_pkey_nid = EVP_PKEY_EC;
			test_sig_nid = OBJ_sn2nid("TEST-SIG-OID");
			test_digest_nid = EVP_MD_get_type(digest);
			test_pkey_nid = OBJ_sn2nid("TEST-KEY-OID");
			success = OBJ_add_sigid(test_sig_nid, digest_id, test_pkey_nid);
			if (!success) {
				PKI_DEBUG("Cannot add new signature ID for TEST-SIG-OID (sig: %d, digest: %d, pkey: %d)",
					test_sig_nid, digest_id, test_pkey_nid);
			} else {
				PKI_DEBUG("Added new signature ID for TEST-SIG-OID");

				test_sig_nid = OBJ_sn2nid("TEST-SIG-OID");
				test_pkey_nid = OBJ_sn2nid("TEST-KEY-OID");
				success = OBJ_find_sigid_algs(test_sig_nid, &test_digest_nid, &test_pkey_nid);
				if (!success) {
					PKI_DEBUG("Cannot find algorithm components from signature id (%d)", test_sig_nid);
				} else {
					PKI_DEBUG("Found new signature ID for TEST-SIG-OID");
				}

				success = OBJ_find_sigid_by_algs(&test_sig_nid, test_digest_nid, test_pkey_nid);
				if (!success) {
					PKI_DEBUG("Cannot find new signature ID from hash (%d) and pkey (%d)",
						test_digest_nid, test_pkey_nid);
				} else {
					PKI_DEBUG("Found new signature ID for TEST-SIG-OID");
				}
				
			}
		}
	}


	PKI_DEBUG("===== END: Extra Experimental OID stuff for DEBUGGING =====");

	// All Done
	return 1;
}

